name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark

      - name: Push snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout --orphan snake-output
          git rm -rf .
          cp dist/snake.svg .
          git add snake.svg
          git commit -m "Update snake"
          git push --force origin snake-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
